name: All-In-One-Action
author: Wuemeli

on:
  pull_request:
    types: [opened]
  issue:
    types: [opened]
  commit:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Wuemeli/all-in-one-action@main
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          TENOR_TOKEN: ${{secrets.TENOR_TOKEN}}
          WEBHOOK: ${{secrets.WEBHOOK}}
